name: Deploy Vue 2 Frontend

on:
  push:
    branches:
      - master  # 监听 master 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub Actions 提供的 Ubuntu 环境

    steps:
    # 1. 检出代码
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. 设置 SSH 密钥和配置 SSH 连接
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}  # 从 GitHub Secrets 获取私钥

    # 3. 执行部署命令
    - name: Deploy with rsync
      run: |
        echo "Deploying to ${{ secrets.SERVER_USER }}@$${{ secrets.SERVER_HOST }}"
        rsync -avz --delete ./dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/cygdrive/c/nginx-1.26.2/html
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
