name: Deploy Vue 2 Frontend

on:
  push:
    branches:
      - master  # 监控 master 分支的提交

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. 打包并部署到服务器
    - name: Debug and Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}               # 服务器 IP
        username: ${{ secrets.SERVER_USER }}           # SSH 用户名
        key: ${{ secrets.SERVER_SSH_KEY }}             # 私钥（存储在 GitHub Secrets）
        port: ${{ secrets.SERVER_PORT }}               # SSH 端口
        script: |
        
          powershell -Command "
            Write-Host 'GitHub Workspace Path: ' $env:GITHUB_WORKSPACE;
            Write-Host 'Dist Folder: ' '${{ github.workspace }}\\dist';
            Remove-Item -Recurse -Force C:\nginx-1.26.2\html\*;
            Copy-Item -Recurse '${{ github.workspace }}\\dist\\*' 'C:\\nginx-1.26.2\\html\\'
          "
