name: Deploy Vue Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 打包 Vue 项目
      - name: Install and Build Vue
        run: |
          npm install
          npm run build

      # 3. 上传文件到服务器
      - name: Upload files to server
        run: |
          scp -i ~/.ssh/id_rsa -P 22 -r dist/ Administrator@116.205.118.87:C:\\nginx-1.26.2\\html\\
