name: Deploy Vue Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 打包 Vue 项目
      - name: Install and Build Vue
        run: |
          npm install
          npm run build

      # 3. 配置 SSH
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          # 使用 printf 来避免换行符问题
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # 添加目标服务器的公钥到 known_hosts
          ssh-keyscan -p 22 116.205.118.87 >> ~/.ssh/known_hosts

          # 调试输出密钥和 known_hosts 是否配置正确
          ls -al ~/.ssh
          cat ~/.ssh/id_rsa
          cat ~/.ssh/known_hosts

      # 4. 上传文件到服务器
      - name: Upload files to server
        run: |
          scp -i ~/.ssh/id_rsa -P 22 -r dist/ Administrator@116.205.118.87:C:/nginx-1.26.2/html/